/**
 * Contract pins. MCP tools/list is pinned to a fixture — clients cache
 * schemas at connect time and the payload is data-independent. Data-backed
 * endpoints are asserted structurally instead: value pins there broke on
 * every snapshot refresh and had already been softened twice.
 * Fixture regenerated by `bun scripts/capture-golden.ts`.
 */

import { beforeAll, describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { createApp } from "../src/server/app";
import { jsonOf, openSnapshot, postMcp } from "./helpers";

const UA = "unitedstarlinktracker.com";
const load = (name: string) => JSON.parse(readFileSync(`tests/golden/${name}`, "utf8"));

let app: ReturnType<typeof createApp>;

beforeAll(() => {
  app = createApp(openSnapshot());
});

describe("MCP protocol contract", () => {
  test("initialize: protocol shape (instructions embed live fleet stats — no value pin)", async () => {
    const live = await postMcp(app, UA, "initialize", {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "golden", version: "1" },
    });
    expect(live.jsonrpc).toBe("2.0");
    expect(live.id).toBe(1);
    expect(typeof live.result.protocolVersion).toBe("string");
    expect(live.result.capabilities.tools).toBeDefined();
    expect(typeof live.result.serverInfo.name).toBe("string");
    expect(live.result.instructions).toContain("United Airlines Starlink tracker");
  });

  test("tools/list matches the pinned fixture exactly (clients cache schemas at connect time)", async () => {
    const live = await postMcp(app, UA, "tools/list", {});
    expect(live).toEqual(load("mcp-tools-list.json"));
  });
});

describe("/api/data structural contract", () => {
  test("shape and cross-field invariants", async () => {
    const live = await jsonOf(app, "/api/data", UA);

    expect(Object.keys(live).sort()).toEqual([
      "fleetStats",
      "flightsByTail",
      "lastUpdated",
      "starlinkPlanes",
      "totalCount",
    ]);
    expect(typeof live.totalCount).toBe("number");
    expect(live.totalCount).toBeGreaterThan(0);
    expect(Number.isNaN(Date.parse(live.lastUpdated))).toBe(false);

    expect(Array.isArray(live.starlinkPlanes)).toBe(true);
    expect(live.starlinkPlanes.length).toBeGreaterThan(0);
    const plane = live.starlinkPlanes[0];
    for (const key of ["Aircraft", "WiFi", "DateFound", "TailNumber", "OperatedBy", "fleet"]) {
      expect(key in plane, `starlinkPlanes row missing ${key}`).toBe(true);
    }
    expect(typeof plane.Aircraft).toBe("string");
    expect(typeof plane.TailNumber).toBe("string");
    expect(typeof plane.OperatedBy).toBe("string");
    expect(["express", "mainline"]).toContain(plane.fleet);

    for (const fleet of ["express", "mainline"] as const) {
      const s = live.fleetStats[fleet];
      expect(typeof s.total).toBe("number");
      expect(typeof s.starlink).toBe("number");
      expect(s.percentage).toBeGreaterThanOrEqual(0);
      expect(s.percentage).toBeLessThanOrEqual(100);
    }
    // Subfleet breakdown must sum to the table so the hero rings agree.
    expect(live.fleetStats.express.starlink + live.fleetStats.mainline.starlink).toBe(
      live.starlinkPlanes.length
    );

    // Every flightsByTail key must be a Starlink tail (subset — stays
    // meaningful even when the snapshot's flight window has fully aged out).
    const starlinkTails = new Set(
      live.starlinkPlanes.map((p: { TailNumber: string }) => p.TailNumber)
    );
    for (const tail of Object.keys(live.flightsByTail)) {
      expect(starlinkTails.has(tail), `flightsByTail key ${tail} not in starlinkPlanes`).toBe(true);
      expect(Array.isArray(live.flightsByTail[tail]), `flightsByTail[${tail}]`).toBe(true);
    }
    // Flight entry shape (website renders these fields).
    const someTail = Object.keys(live.flightsByTail)[0];
    if (someTail) {
      const f = live.flightsByTail[someTail][0];
      expect(typeof f.tail_number).toBe("string");
      expect(typeof f.flight_number).toBe("string");
      expect(typeof f.departure_airport).toBe("string");
      expect(typeof f.arrival_airport).toBe("string");
      expect(typeof f.departure_time).toBe("number");
      expect(typeof f.arrival_time).toBe("number");
    }
  });
});
