/**
 * IATA -> airport name + city for every airport in the tracked route network.
 * Static reference facts (OurAirports-style public data), keyed to the same
 * vocabulary as airport-geo.ts — tests/airport-names.test.ts pins that every
 * coordinate entry has a name here, so a new airport entering the network
 * fails loud instead of shipping a nameless page. City is the SERP-facing
 * word ("Newark Starlink flights"), so it is the common metro name, not the
 * airport's municipal address.
 */

export interface AirportInfo {
  name: string;
  city: string;
}

// biome-ignore format: one airport per line keeps the table diffable
export const AIRPORT_NAMES: Record<string, AirportInfo> = {
  ABE: { name: "Lehigh Valley International Airport", city: "Allentown" },
  ABI: { name: "Abilene Regional Airport", city: "Abilene" },
  ABJ: { name: "Félix-Houphouët-Boigny International Airport", city: "Abidjan" },
  ABQ: { name: "Albuquerque International Sunport", city: "Albuquerque" },
  ACA: { name: "Acapulco International Airport", city: "Acapulco" },
  ACC: { name: "Kotoka International Airport", city: "Accra" },
  ACK: { name: "Nantucket Memorial Airport", city: "Nantucket" },
  ACV: { name: "California Redwood Coast-Humboldt County Airport", city: "Arcata" },
  ADD: { name: "Addis Ababa Bole International Airport", city: "Addis Ababa" },
  ADL: { name: "Adelaide Airport", city: "Adelaide" },
  ADQ: { name: "Kodiak Airport", city: "Kodiak" },
  AEX: { name: "Alexandria International Airport", city: "Alexandria" },
  AGP: { name: "Málaga-Costa del Sol Airport", city: "Málaga" },
  AGU: { name: "Aguascalientes International Airport", city: "Aguascalientes" },
  AKL: { name: "Auckland Airport", city: "Auckland" },
  AKN: { name: "King Salmon Airport", city: "King Salmon" },
  ALB: { name: "Albany International Airport", city: "Albany" },
  ALG: { name: "Houari Boumediene Airport", city: "Algiers" },
  ALW: { name: "Walla Walla Regional Airport", city: "Walla Walla" },
  AMA: { name: "Rick Husband Amarillo International Airport", city: "Amarillo" },
  AMD: { name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad" },
  AMM: { name: "Queen Alia International Airport", city: "Amman" },
  AMS: { name: "Amsterdam Airport Schiphol", city: "Amsterdam" },
  ANC: { name: "Ted Stevens Anchorage International Airport", city: "Anchorage" },
  ARN: { name: "Stockholm Arlanda Airport", city: "Stockholm" },
  ASE: { name: "Aspen/Pitkin County Airport", city: "Aspen" },
  ATH: { name: "Athens International Airport", city: "Athens" },
  ATL: { name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta" },
  ATW: { name: "Appleton International Airport", city: "Appleton" },
  ATY: { name: "Watertown Regional Airport", city: "Watertown" },
  AUA: { name: "Queen Beatrix International Airport", city: "Aruba" },
  AUH: { name: "Zayed International Airport", city: "Abu Dhabi" },
  AUS: { name: "Austin-Bergstrom International Airport", city: "Austin" },
  AVL: { name: "Asheville Regional Airport", city: "Asheville" },
  AVP: { name: "Wilkes-Barre/Scranton International Airport", city: "Scranton" },
  BAH: { name: "Bahrain International Airport", city: "Manama" },
  BCN: { name: "Josep Tarradellas Barcelona-El Prat Airport", city: "Barcelona" },
  BDL: { name: "Bradley International Airport", city: "Hartford" },
  BER: { name: "Berlin Brandenburg Airport", city: "Berlin" },
  BET: { name: "Bethel Airport", city: "Bethel" },
  BEY: { name: "Beirut-Rafic Hariri International Airport", city: "Beirut" },
  BFF: { name: "Western Nebraska Regional Airport", city: "Scottsbluff" },
  BFI: { name: "Boeing Field/King County International Airport", city: "Seattle" },
  BFL: { name: "Meadows Field Airport", city: "Bakersfield" },
  BGI: { name: "Grantley Adams International Airport", city: "Bridgetown" },
  BGR: { name: "Bangor International Airport", city: "Bangor" },
  BGW: { name: "Baghdad International Airport", city: "Baghdad" },
  BHM: { name: "Birmingham-Shuttlesworth International Airport", city: "Birmingham" },
  BHX: { name: "Birmingham Airport", city: "Birmingham" },
  BIH: { name: "Eastern Sierra Regional Airport", city: "Bishop" },
  BIL: { name: "Billings Logan International Airport", city: "Billings" },
  BIS: { name: "Bismarck Municipal Airport", city: "Bismarck" },
  BJX: { name: "Del Bajío International Airport", city: "León" },
  BKK: { name: "Suvarnabhumi Airport", city: "Bangkok" },
  BLI: { name: "Bellingham International Airport", city: "Bellingham" },
  BLR: { name: "Kempegowda International Airport", city: "Bengaluru" },
  BNA: { name: "Nashville International Airport", city: "Nashville" },
  BNE: { name: "Brisbane Airport", city: "Brisbane" },
  BOG: { name: "El Dorado International Airport", city: "Bogotá" },
  BOI: { name: "Boise Airport", city: "Boise" },
  BOM: { name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai" },
  BON: { name: "Flamingo International Airport", city: "Bonaire" },
  BOS: { name: "Boston Logan International Airport", city: "Boston" },
  BQN: { name: "Rafael Hernández International Airport", city: "Aguadilla" },
  BRO: { name: "Brownsville/South Padre Island International Airport", city: "Brownsville" },
  BRU: { name: "Brussels Airport", city: "Brussels" },
  BRW: { name: "Wiley Post-Will Rogers Memorial Airport", city: "Utqiagvik" },
  BSR: { name: "Basra International Airport", city: "Basra" },
  BTM: { name: "Bert Mooney Airport", city: "Butte" },
  BTR: { name: "Baton Rouge Metropolitan Airport", city: "Baton Rouge" },
  BTV: { name: "Burlington International Airport", city: "Burlington" },
  BUD: { name: "Budapest Ferenc Liszt International Airport", city: "Budapest" },
  BUF: { name: "Buffalo Niagara International Airport", city: "Buffalo" },
  BUR: { name: "Hollywood Burbank Airport", city: "Burbank" },
  BWI: { name: "Baltimore/Washington International Thurgood Marshall Airport", city: "Baltimore" },
  BZE: { name: "Philip S. W. Goldson International Airport", city: "Belize City" },
  BZN: { name: "Bozeman Yellowstone International Airport", city: "Bozeman" },
  CAE: { name: "Columbia Metropolitan Airport", city: "Columbia" },
  CAI: { name: "Cairo International Airport", city: "Cairo" },
  CAK: { name: "Akron-Canton Airport", city: "Akron" },
  CAN: { name: "Guangzhou Baiyun International Airport", city: "Guangzhou" },
  CCU: { name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata" },
  CDG: { name: "Paris Charles de Gaulle Airport", city: "Paris" },
  CGK: { name: "Soekarno-Hatta International Airport", city: "Jakarta" },
  CHA: { name: "Chattanooga Metropolitan Airport", city: "Chattanooga" },
  CHO: { name: "Charlottesville-Albemarle Airport", city: "Charlottesville" },
  CHS: { name: "Charleston International Airport", city: "Charleston" },
  CID: { name: "The Eastern Iowa Airport", city: "Cedar Rapids" },
  CIU: { name: "Chippewa County International Airport", city: "Sault Ste. Marie" },
  CKB: { name: "North Central West Virginia Airport", city: "Clarksburg" },
  CKG: { name: "Chongqing Jiangbei International Airport", city: "Chongqing" },
  CLD: { name: "McClellan-Palomar Airport", city: "Carlsbad" },
  CLE: { name: "Cleveland Hopkins International Airport", city: "Cleveland" },
  CLT: { name: "Charlotte Douglas International Airport", city: "Charlotte" },
  CMB: { name: "Bandaranaike International Airport", city: "Colombo" },
  CMH: { name: "John Glenn Columbus International Airport", city: "Columbus" },
  CMN: { name: "Mohammed V International Airport", city: "Casablanca" },
  CMX: { name: "Houghton County Memorial Airport", city: "Houghton" },
  COD: { name: "Yellowstone Regional Airport", city: "Cody" },
  COK: { name: "Cochin International Airport", city: "Kochi" },
  COS: { name: "Colorado Springs Airport", city: "Colorado Springs" },
  COU: { name: "Columbia Regional Airport", city: "Columbia" },
  CPH: { name: "Copenhagen Airport", city: "Copenhagen" },
  CPR: { name: "Casper-Natrona County International Airport", city: "Casper" },
  CPT: { name: "Cape Town International Airport", city: "Cape Town" },
  CRK: { name: "Clark International Airport", city: "Clark" },
  CRP: { name: "Corpus Christi International Airport", city: "Corpus Christi" },
  CRW: { name: "West Virginia International Yeager Airport", city: "Charleston" },
  CUN: { name: "Cancún International Airport", city: "Cancún" },
  CUR: { name: "Curaçao International Airport", city: "Curaçao" },
  CVG: { name: "Cincinnati/Northern Kentucky International Airport", city: "Cincinnati" },
  CYS: { name: "Cheyenne Regional Airport", city: "Cheyenne" },
  CZM: { name: "Cozumel International Airport", city: "Cozumel" },
  DAC: { name: "Hazrat Shahjalal International Airport", city: "Dhaka" },
  DAM: { name: "Damascus International Airport", city: "Damascus" },
  DAR: { name: "Julius Nyerere International Airport", city: "Dar es Salaam" },
  DAY: { name: "Dayton International Airport", city: "Dayton" },
  DCA: { name: "Ronald Reagan Washington National Airport", city: "Washington" },
  DDC: { name: "Dodge City Regional Airport", city: "Dodge City" },
  DEC: { name: "Decatur Airport", city: "Decatur" },
  DEL: { name: "Indira Gandhi International Airport", city: "Delhi" },
  DEN: { name: "Denver International Airport", city: "Denver" },
  DFW: { name: "Dallas Fort Worth International Airport", city: "Dallas" },
  DIK: { name: "Dickinson Theodore Roosevelt Regional Airport", city: "Dickinson" },
  DLG: { name: "Dillingham Airport", city: "Dillingham" },
  DLH: { name: "Duluth International Airport", city: "Duluth" },
  DMM: { name: "King Fahd International Airport", city: "Dammam" },
  DOH: { name: "Hamad International Airport", city: "Doha" },
  DPS: { name: "I Gusti Ngurah Rai International Airport", city: "Bali" },
  DRO: { name: "Durango-La Plata County Airport", city: "Durango" },
  DSM: { name: "Des Moines International Airport", city: "Des Moines" },
  DTW: { name: "Detroit Metropolitan Wayne County Airport", city: "Detroit" },
  DUB: { name: "Dublin Airport", city: "Dublin" },
  DUR: { name: "King Shaka International Airport", city: "Durban" },
  DVL: { name: "Devils Lake Regional Airport", city: "Devils Lake" },
  DXB: { name: "Dubai International Airport", city: "Dubai" },
  EAR: { name: "Kearney Regional Airport", city: "Kearney" },
  EAT: { name: "Pangborn Memorial Airport", city: "Wenatchee" },
  EAU: { name: "Chippewa Valley Regional Airport", city: "Eau Claire" },
  ECP: { name: "Northwest Florida Beaches International Airport", city: "Panama City Beach" },
  EDI: { name: "Edinburgh Airport", city: "Edinburgh" },
  EGE: { name: "Eagle County Regional Airport", city: "Vail" },
  ELP: { name: "El Paso International Airport", city: "El Paso" },
  EUG: { name: "Eugene Airport", city: "Eugene" },
  EWR: { name: "Newark Liberty International Airport", city: "Newark" },
  EYW: { name: "Key West International Airport", city: "Key West" },
  EZE: { name: "Ministro Pistarini International Airport", city: "Buenos Aires" },
  FAI: { name: "Fairbanks International Airport", city: "Fairbanks" },
  FAR: { name: "Hector International Airport", city: "Fargo" },
  FAT: { name: "Fresno Yosemite International Airport", city: "Fresno" },
  FCA: { name: "Glacier Park International Airport", city: "Kalispell" },
  FCO: { name: "Rome Fiumicino Airport", city: "Rome" },
  FLL: { name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale" },
  FMN: { name: "Four Corners Regional Airport", city: "Farmington" },
  FNT: { name: "Bishop International Airport", city: "Flint" },
  FOD: { name: "Fort Dodge Regional Airport", city: "Fort Dodge" },
  FRA: { name: "Frankfurt Airport", city: "Frankfurt" },
  FSD: { name: "Sioux Falls Regional Airport", city: "Sioux Falls" },
  FWA: { name: "Fort Wayne International Airport", city: "Fort Wayne" },
  GCC: { name: "Northeast Wyoming Regional Airport", city: "Gillette" },
  GCM: { name: "Owen Roberts International Airport", city: "Grand Cayman" },
  GDL: { name: "Guadalajara International Airport", city: "Guadalajara" },
  GEG: { name: "Spokane International Airport", city: "Spokane" },
  GGE: { name: "Georgetown County Airport", city: "Georgetown" },
  GIG: { name: "Rio de Janeiro-Galeão International Airport", city: "Rio de Janeiro" },
  GJT: { name: "Grand Junction Regional Airport", city: "Grand Junction" },
  GPT: { name: "Gulfport-Biloxi International Airport", city: "Gulfport" },
  GRB: { name: "Green Bay Austin Straubel International Airport", city: "Green Bay" },
  GRR: { name: "Gerald R. Ford International Airport", city: "Grand Rapids" },
  GRU: { name: "São Paulo/Guarulhos International Airport", city: "São Paulo" },
  GSO: { name: "Piedmont Triad International Airport", city: "Greensboro" },
  GSP: { name: "Greenville-Spartanburg International Airport", city: "Greenville" },
  GTF: { name: "Great Falls International Airport", city: "Great Falls" },
  GUA: { name: "La Aurora International Airport", city: "Guatemala City" },
  GUC: { name: "Gunnison-Crested Butte Regional Airport", city: "Gunnison" },
  GUM: { name: "Antonio B. Won Pat International Airport", city: "Guam" },
  GVA: { name: "Geneva Airport", city: "Geneva" },
  HAN: { name: "Noi Bai International Airport", city: "Hanoi" },
  HDN: { name: "Yampa Valley Airport", city: "Steamboat Springs" },
  HEL: { name: "Helsinki-Vantaa Airport", city: "Helsinki" },
  HGH: { name: "Hangzhou Xiaoshan International Airport", city: "Hangzhou" },
  HHH: { name: "Hilton Head Island Airport", city: "Hilton Head" },
  HKG: { name: "Hong Kong International Airport", city: "Hong Kong" },
  HKT: { name: "Phuket International Airport", city: "Phuket" },
  HLN: { name: "Helena Regional Airport", city: "Helena" },
  HND: { name: "Tokyo Haneda Airport", city: "Tokyo" },
  HNL: { name: "Daniel K. Inouye International Airport", city: "Honolulu" },
  HOB: { name: "Lea County Regional Airport", city: "Hobbs" },
  HRL: { name: "Valley International Airport", city: "Harlingen" },
  HSV: { name: "Huntsville International Airport", city: "Huntsville" },
  HYD: { name: "Rajiv Gandhi International Airport", city: "Hyderabad" },
  HYS: { name: "Hays Regional Airport", city: "Hays" },
  IAB: { name: "McConnell Air Force Base", city: "Wichita" },
  IAD: { name: "Washington Dulles International Airport", city: "Washington" },
  IAH: { name: "George Bush Intercontinental Airport", city: "Houston" },
  ICN: { name: "Incheon International Airport", city: "Seoul" },
  ICT: { name: "Wichita Dwight D. Eisenhower National Airport", city: "Wichita" },
  IDA: { name: "Idaho Falls Regional Airport", city: "Idaho Falls" },
  ILM: { name: "Wilmington International Airport", city: "Wilmington" },
  IND: { name: "Indianapolis International Airport", city: "Indianapolis" },
  INT: { name: "Smith Reynolds Airport", city: "Winston-Salem" },
  ISB: { name: "Islamabad International Airport", city: "Islamabad" },
  IST: { name: "Istanbul Airport", city: "Istanbul" },
  ITH: { name: "Ithaca Tompkins International Airport", city: "Ithaca" },
  ITO: { name: "Hilo International Airport", city: "Hilo" },
  JAC: { name: "Jackson Hole Airport", city: "Jackson Hole" },
  JAN: { name: "Jackson-Medgar Wiley Evers International Airport", city: "Jackson" },
  JAX: { name: "Jacksonville International Airport", city: "Jacksonville" },
  JED: { name: "King Abdulaziz International Airport", city: "Jeddah" },
  JFK: { name: "John F. Kennedy International Airport", city: "New York" },
  JLN: { name: "Joplin Regional Airport", city: "Joplin" },
  JMS: { name: "Jamestown Regional Airport", city: "Jamestown" },
  JNB: { name: "O. R. Tambo International Airport", city: "Johannesburg" },
  JNU: { name: "Juneau International Airport", city: "Juneau" },
  JST: { name: "Johnstown-Cambria County Airport", city: "Johnstown" },
  KEF: { name: "Keflavík International Airport", city: "Reykjavík" },
  KHI: { name: "Jinnah International Airport", city: "Karachi" },
  KIN: { name: "Norman Manley International Airport", city: "Kingston" },
  KIX: { name: "Kansai International Airport", city: "Osaka" },
  KOA: { name: "Ellison Onizuka Kona International Airport", city: "Kona" },
  KSA: { name: "Kosrae International Airport", city: "Kosrae" },
  KTM: { name: "Tribhuvan International Airport", city: "Kathmandu" },
  KTN: { name: "Ketchikan International Airport", city: "Ketchikan" },
  KUL: { name: "Kuala Lumpur International Airport", city: "Kuala Lumpur" },
  KWA: { name: "Bucholz Army Airfield", city: "Kwajalein" },
  KWI: { name: "Kuwait International Airport", city: "Kuwait City" },
  LAF: { name: "Purdue University Airport", city: "Lafayette" },
  LAP: { name: "La Paz International Airport", city: "La Paz" },
  LAR: { name: "Laramie Regional Airport", city: "Laramie" },
  LAS: { name: "Harry Reid International Airport", city: "Las Vegas" },
  LAX: { name: "Los Angeles International Airport", city: "Los Angeles" },
  LBB: { name: "Lubbock Preston Smith International Airport", city: "Lubbock" },
  LBF: { name: "North Platte Regional Airport", city: "North Platte" },
  LBL: { name: "Liberal Mid-America Regional Airport", city: "Liberal" },
  LCA: { name: "Larnaca International Airport", city: "Larnaca" },
  LCH: { name: "Lake Charles Regional Airport", city: "Lake Charles" },
  LEX: { name: "Blue Grass Airport", city: "Lexington" },
  LFT: { name: "Lafayette Regional Airport", city: "Lafayette" },
  LGA: { name: "LaGuardia Airport", city: "New York" },
  LGB: { name: "Long Beach Airport", city: "Long Beach" },
  LGW: { name: "London Gatwick Airport", city: "London" },
  LHE: { name: "Allama Iqbal International Airport", city: "Lahore" },
  LHR: { name: "London Heathrow Airport", city: "London" },
  LIH: { name: "Lihue Airport", city: "Lihue" },
  LIM: { name: "Jorge Chávez International Airport", city: "Lima" },
  LIR: { name: "Daniel Oduber Quirós International Airport", city: "Liberia" },
  LIS: { name: "Lisbon Humberto Delgado Airport", city: "Lisbon" },
  LIT: { name: "Bill and Hillary Clinton National Airport", city: "Little Rock" },
  LNK: { name: "Lincoln Airport", city: "Lincoln" },
  LOS: { name: "Murtala Muhammed International Airport", city: "Lagos" },
  LRD: { name: "Laredo International Airport", city: "Laredo" },
  LTO: { name: "Loreto International Airport", city: "Loreto" },
  LYH: { name: "Lynchburg Regional Airport", city: "Lynchburg" },
  MAA: { name: "Chennai International Airport", city: "Chennai" },
  MAD: { name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid" },
  MAF: { name: "Midland International Air and Space Port", city: "Midland" },
  MAJ: { name: "Marshall Islands International Airport", city: "Majuro" },
  MAN: { name: "Manchester Airport", city: "Manchester" },
  MBJ: { name: "Sangster International Airport", city: "Montego Bay" },
  MBS: { name: "MBS International Airport", city: "Saginaw" },
  MCI: { name: "Kansas City International Airport", city: "Kansas City" },
  MCN: { name: "Middle Georgia Regional Airport", city: "Macon" },
  MCO: { name: "Orlando International Airport", city: "Orlando" },
  MCT: { name: "Muscat International Airport", city: "Muscat" },
  MCW: { name: "Mason City Municipal Airport", city: "Mason City" },
  MDT: { name: "Harrisburg International Airport", city: "Harrisburg" },
  MDW: { name: "Chicago Midway International Airport", city: "Chicago" },
  MED: { name: "Prince Mohammad bin Abdulaziz International Airport", city: "Medina" },
  MEI: { name: "Meridian Regional Airport", city: "Meridian" },
  MEL: { name: "Melbourne Airport", city: "Melbourne" },
  MEM: { name: "Memphis International Airport", city: "Memphis" },
  MEX: { name: "Mexico City International Airport", city: "Mexico City" },
  MFE: { name: "McAllen International Airport", city: "McAllen" },
  MFR: { name: "Rogue Valley International-Medford Airport", city: "Medford" },
  MGA: { name: "Augusto C. Sandino International Airport", city: "Managua" },
  MGM: { name: "Montgomery Regional Airport", city: "Montgomery" },
  MGW: { name: "Morgantown Municipal Airport", city: "Morgantown" },
  MHT: { name: "Manchester-Boston Regional Airport", city: "Manchester" },
  MIA: { name: "Miami International Airport", city: "Miami" },
  MID: { name: "Mérida International Airport", city: "Mérida" },
  MKC: { name: "Charles B. Wheeler Downtown Airport", city: "Kansas City" },
  MKE: { name: "Milwaukee Mitchell International Airport", city: "Milwaukee" },
  MLB: { name: "Melbourne Orlando International Airport", city: "Melbourne" },
  MLE: { name: "Velana International Airport", city: "Malé" },
  MLI: { name: "Quad City International Airport", city: "Moline" },
  MLM: { name: "Morelia International Airport", city: "Morelia" },
  MNL: { name: "Ninoy Aquino International Airport", city: "Manila" },
  MOB: { name: "Mobile Regional Airport", city: "Mobile" },
  MOT: { name: "Minot International Airport", city: "Minot" },
  MPM: { name: "Maputo International Airport", city: "Maputo" },
  MRY: { name: "Monterey Regional Airport", city: "Monterey" },
  MSN: { name: "Dane County Regional Airport", city: "Madison" },
  MSO: { name: "Missoula Montana Airport", city: "Missoula" },
  MSP: { name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis" },
  MSY: { name: "Louis Armstrong New Orleans International Airport", city: "New Orleans" },
  MTJ: { name: "Montrose Regional Airport", city: "Montrose" },
  MTY: { name: "Monterrey International Airport", city: "Monterrey" },
  MUC: { name: "Munich Airport", city: "Munich" },
  MXP: { name: "Milan Malpensa Airport", city: "Milan" },
  MYR: { name: "Myrtle Beach International Airport", city: "Myrtle Beach" },
  MZT: { name: "Mazatlán International Airport", city: "Mazatlán" },
  NAS: { name: "Lynden Pindling International Airport", city: "Nassau" },
  NBO: { name: "Jomo Kenyatta International Airport", city: "Nairobi" },
  NCE: { name: "Nice Côte d'Azur Airport", city: "Nice" },
  NRT: { name: "Narita International Airport", city: "Tokyo" },
  OAK: { name: "Oakland International Airport", city: "Oakland" },
  OAX: { name: "Oaxaca International Airport", city: "Oaxaca" },
  OGG: { name: "Kahului Airport", city: "Maui" },
  OKC: { name: "Will Rogers World Airport", city: "Oklahoma City" },
  OMA: { name: "Eppley Airfield", city: "Omaha" },
  OME: { name: "Nome Airport", city: "Nome" },
  ONT: { name: "Ontario International Airport", city: "Ontario" },
  OPO: { name: "Porto Airport", city: "Porto" },
  ORD: { name: "Chicago O'Hare International Airport", city: "Chicago" },
  ORF: { name: "Norfolk International Airport", city: "Norfolk" },
  OSL: { name: "Oslo Gardermoen Airport", city: "Oslo" },
  OTH: { name: "Southwest Oregon Regional Airport", city: "North Bend" },
  OTZ: { name: "Ralph Wien Memorial Airport", city: "Kotzebue" },
  PAE: { name: "Seattle Paine Field International Airport", city: "Everett" },
  PAH: { name: "Barkley Regional Airport", city: "Paducah" },
  PBI: { name: "Palm Beach International Airport", city: "West Palm Beach" },
  PDX: { name: "Portland International Airport", city: "Portland" },
  PEK: { name: "Beijing Capital International Airport", city: "Beijing" },
  PER: { name: "Perth Airport", city: "Perth" },
  PHL: { name: "Philadelphia International Airport", city: "Philadelphia" },
  PHX: { name: "Phoenix Sky Harbor International Airport", city: "Phoenix" },
  PIA: { name: "General Wayne A. Downing Peoria International Airport", city: "Peoria" },
  PIB: { name: "Hattiesburg-Laurel Regional Airport", city: "Hattiesburg" },
  PIR: { name: "Pierre Regional Airport", city: "Pierre" },
  PIT: { name: "Pittsburgh International Airport", city: "Pittsburgh" },
  PKX: { name: "Beijing Daxing International Airport", city: "Beijing" },
  PLN: { name: "Pellston Regional Airport", city: "Pellston" },
  PLS: { name: "Providenciales International Airport", city: "Providenciales" },
  PNI: { name: "Pohnpei International Airport", city: "Pohnpei" },
  PNS: { name: "Pensacola International Airport", city: "Pensacola" },
  PPG: { name: "Pago Pago International Airport", city: "Pago Pago" },
  PPT: { name: "Faa'a International Airport", city: "Papeete" },
  PRC: { name: "Prescott Regional Airport", city: "Prescott" },
  PSC: { name: "Tri-Cities Airport", city: "Pasco" },
  PSG: { name: "Petersburg James A. Johnson Airport", city: "Petersburg" },
  PSP: { name: "Palm Springs International Airport", city: "Palm Springs" },
  PTY: { name: "Tocumen International Airport", city: "Panama City" },
  PUJ: { name: "Punta Cana International Airport", city: "Punta Cana" },
  PUW: { name: "Pullman-Moscow Regional Airport", city: "Pullman" },
  PVD: { name: "Rhode Island T. F. Green International Airport", city: "Providence" },
  PVG: { name: "Shanghai Pudong International Airport", city: "Shanghai" },
  PVR: { name: "Puerto Vallarta International Airport", city: "Puerto Vallarta" },
  PWM: { name: "Portland International Jetport", city: "Portland" },
  PXM: { name: "Puerto Escondido International Airport", city: "Puerto Escondido" },
  QRO: { name: "Querétaro International Airport", city: "Querétaro" },
  RAK: { name: "Marrakesh Menara Airport", city: "Marrakesh" },
  RAP: { name: "Rapid City Regional Airport", city: "Rapid City" },
  RAR: { name: "Rarotonga International Airport", city: "Rarotonga" },
  RDD: { name: "Redding Regional Airport", city: "Redding" },
  RDM: { name: "Redmond Municipal Airport", city: "Bend" },
  RDU: { name: "Raleigh-Durham International Airport", city: "Raleigh" },
  RFD: { name: "Chicago Rockford International Airport", city: "Rockford" },
  RHI: { name: "Rhinelander-Oneida County Airport", city: "Rhinelander" },
  RIC: { name: "Richmond International Airport", city: "Richmond" },
  RIW: { name: "Central Wyoming Regional Airport", city: "Riverton" },
  RKS: { name: "Southwest Wyoming Regional Airport", city: "Rock Springs" },
  RNO: { name: "Reno-Tahoe International Airport", city: "Reno" },
  ROA: { name: "Roanoke-Blacksburg Regional Airport", city: "Roanoke" },
  ROC: { name: "Frederick Douglass Greater Rochester International Airport", city: "Rochester" },
  ROR: { name: "Roman Tmetuchl International Airport", city: "Koror" },
  ROW: { name: "Roswell Air Center", city: "Roswell" },
  RSW: { name: "Southwest Florida International Airport", city: "Fort Myers" },
  RTB: { name: "Juan Manuel Gálvez International Airport", city: "Roatán" },
  RUH: { name: "King Khalid International Airport", city: "Riyadh" },
  SAF: { name: "Santa Fe Regional Airport", city: "Santa Fe" },
  SAL: { name: "El Salvador International Airport", city: "San Salvador" },
  SAN: { name: "San Diego International Airport", city: "San Diego" },
  SAP: { name: "Ramón Villeda Morales International Airport", city: "San Pedro Sula" },
  SAT: { name: "San Antonio International Airport", city: "San Antonio" },
  SAV: { name: "Savannah/Hilton Head International Airport", city: "Savannah" },
  SBA: { name: "Santa Barbara Airport", city: "Santa Barbara" },
  SBN: { name: "South Bend International Airport", city: "South Bend" },
  SBP: { name: "San Luis Obispo County Regional Airport", city: "San Luis Obispo" },
  SCC: { name: "Deadhorse Airport", city: "Deadhorse" },
  SCE: { name: "University Park Airport", city: "State College" },
  SCL: { name: "Arturo Merino Benítez International Airport", city: "Santiago" },
  SDF: { name: "Louisville Muhammad Ali International Airport", city: "Louisville" },
  SDQ: { name: "Las Américas International Airport", city: "Santo Domingo" },
  SEA: { name: "Seattle-Tacoma International Airport", city: "Seattle" },
  SEZ: { name: "Seychelles International Airport", city: "Mahé" },
  SFO: { name: "San Francisco International Airport", city: "San Francisco" },
  SGF: { name: "Springfield-Branson National Airport", city: "Springfield" },
  SGN: { name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City" },
  SGU: { name: "St. George Regional Airport", city: "St. George" },
  SHR: { name: "Sheridan County Airport", city: "Sheridan" },
  SHV: { name: "Shreveport Regional Airport", city: "Shreveport" },
  SIN: { name: "Singapore Changi Airport", city: "Singapore" },
  SIT: { name: "Sitka Rocky Gutierrez Airport", city: "Sitka" },
  SJC: { name: "San José Mineta International Airport", city: "San Jose" },
  SJD: { name: "Los Cabos International Airport", city: "Los Cabos" },
  SJO: { name: "Juan Santamaría International Airport", city: "San José" },
  SJU: { name: "Luis Muñoz Marín International Airport", city: "San Juan" },
  SLC: { name: "Salt Lake City International Airport", city: "Salt Lake City" },
  SLN: { name: "Salina Regional Airport", city: "Salina" },
  SLP: { name: "San Luis Potosí International Airport", city: "San Luis Potosí" },
  SMF: { name: "Sacramento International Airport", city: "Sacramento" },
  SNA: { name: "John Wayne Airport", city: "Orange County" },
  SNN: { name: "Shannon Airport", city: "Shannon" },
  SPN: { name: "Saipan International Airport", city: "Saipan" },
  SRQ: { name: "Sarasota Bradenton International Airport", city: "Sarasota" },
  STI: { name: "Cibao International Airport", city: "Santiago de los Caballeros" },
  STL: { name: "St. Louis Lambert International Airport", city: "St. Louis" },
  STS: { name: "Charles M. Schulz-Sonoma County Airport", city: "Santa Rosa" },
  STT: { name: "Cyril E. King Airport", city: "St. Thomas" },
  STX: { name: "Henry E. Rohlsen Airport", city: "St. Croix" },
  SUN: { name: "Friedman Memorial Airport", city: "Sun Valley" },
  SUX: { name: "Sioux Gateway Airport", city: "Sioux City" },
  SXM: { name: "Princess Juliana International Airport", city: "Sint Maarten" },
  SYD: { name: "Sydney Kingsford Smith Airport", city: "Sydney" },
  SYR: { name: "Syracuse Hancock International Airport", city: "Syracuse" },
  TAM: { name: "Tampico International Airport", city: "Tampico" },
  TEV: { name: "Teruel Airport", city: "Teruel" },
  TKK: { name: "Chuuk International Airport", city: "Chuuk" },
  TLV: { name: "Ben Gurion Airport", city: "Tel Aviv" },
  TPA: { name: "Tampa International Airport", city: "Tampa" },
  TPE: { name: "Taiwan Taoyuan International Airport", city: "Taipei" },
  TPQ: { name: "Tepic International Airport", city: "Tepic" },
  TQO: { name: "Felipe Carrillo Puerto International Airport", city: "Tulum" },
  TUL: { name: "Tulsa International Airport", city: "Tulsa" },
  TUN: { name: "Tunis-Carthage International Airport", city: "Tunis" },
  TUS: { name: "Tucson International Airport", city: "Tucson" },
  TVC: { name: "Cherry Capital Airport", city: "Traverse City" },
  TYS: { name: "McGhee Tyson Airport", city: "Knoxville" },
  UVF: { name: "Hewanorra International Airport", city: "Saint Lucia" },
  VCE: { name: "Venice Marco Polo Airport", city: "Venice" },
  VCT: { name: "Victoria Regional Airport", city: "Victoria" },
  VER: { name: "Veracruz International Airport", city: "Veracruz" },
  VIE: { name: "Vienna International Airport", city: "Vienna" },
  WRG: { name: "Wrangell Airport", city: "Wrangell" },
  WYS: { name: "Yellowstone Airport", city: "West Yellowstone" },
  XFW: { name: "Hamburg Finkenwerder Airport", city: "Hamburg" },
  XNA: { name: "Northwest Arkansas National Airport", city: "Bentonville" },
  XWA: { name: "Williston Basin International Airport", city: "Williston" },
  YAP: { name: "Yap International Airport", city: "Yap" },
  YEG: { name: "Edmonton International Airport", city: "Edmonton" },
  YHZ: { name: "Halifax Stanfield International Airport", city: "Halifax" },
  YKM: { name: "Yakima Air Terminal", city: "Yakima" },
  YLW: { name: "Kelowna International Airport", city: "Kelowna" },
  YOW: { name: "Ottawa Macdonald-Cartier International Airport", city: "Ottawa" },
  YQB: { name: "Québec City Jean Lesage International Airport", city: "Québec City" },
  YQG: { name: "Windsor International Airport", city: "Windsor" },
  YUL: { name: "Montréal-Trudeau International Airport", city: "Montréal" },
  YVR: { name: "Vancouver International Airport", city: "Vancouver" },
  YWG: { name: "Winnipeg Richardson International Airport", city: "Winnipeg" },
  YYC: { name: "Calgary International Airport", city: "Calgary" },
  YYJ: { name: "Victoria International Airport", city: "Victoria" },
  YYZ: { name: "Toronto Pearson International Airport", city: "Toronto" },
  ZIH: { name: "Ixtapa-Zihuatanejo International Airport", city: "Zihuatanejo" },
  ZLO: { name: "Manzanillo International Airport", city: "Manzanillo" },
  ZRH: { name: "Zurich Airport", city: "Zurich" },
};

export function airportInfo(iata: string): AirportInfo | null {
  return AIRPORT_NAMES[iata] ?? null;
}
